#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := facenet_single_command_line
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../../../components $(PROJECT_PATH)/../../../components/esp_facenet
include $(IDF_PATH)/make/project.mk

