.TH "box_t" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
box_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fptp_t \fBbox_p\fP [4]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "fptp_t box_t::box_p[4]"
box struct 

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
