.TH "dl_matrix3d_t" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dl_matrix3d_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBc\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "int \fBstride\fP"
.br
.ti -1c
.RI "fptp_t * \fBitem\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int dl_matrix3d_t::c"
Channel 
.SS "int dl_matrix3d_t::h"
Height 
.SS "fptp_t* dl_matrix3d_t::item"
Data 
.SS "int dl_matrix3d_t::n"
Number of filter, input and output must be 1 
.SS "int dl_matrix3d_t::stride"
Step between lines 
.SS "int dl_matrix3d_t::w"
Width 

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
