.TH "dl_matrix3dq_blazeblock_config_t" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dl_matrix3dq_blazeblock_config_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstride_x\fP"
.br
.ti -1c
.RI "int \fBstride_y\fP"
.br
.ti -1c
.RI "dl_padding_type \fBpadding\fP"
.br
.ti -1c
.RI "dl_conv_mode \fBmode\fP"
.br
.ti -1c
.RI "int \fBdw1_exponent\fP"
.br
.ti -1c
.RI "int \fBpw1_exponent\fP"
.br
.ti -1c
.RI "int \fBdw2_exponent\fP"
.br
.ti -1c
.RI "int \fBpw2_exponent\fP"
.br
.ti -1c
.RI "int \fBshortcut\fP"
.br
.ti -1c
.RI "int \fBsave_input\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int dl_matrix3dq_blazeblock_config_t::dw1_exponent"
Exponent of dw1 filter 
.SS "int dl_matrix3dq_blazeblock_config_t::dw2_exponent"
Exponent of dw2 filter 
.SS "dl_conv_mode dl_matrix3dq_blazeblock_config_t::mode"
Implementation mode 
.SS "dl_padding_type dl_matrix3dq_blazeblock_config_t::padding"
Padding type 
.SS "int dl_matrix3dq_blazeblock_config_t::pw1_exponent"
Exponent of pw1 filter 
.SS "int dl_matrix3dq_blazeblock_config_t::pw2_exponent"
Exponent of pw2 filter 
.SS "int dl_matrix3dq_blazeblock_config_t::save_input"
Input save flag 
.SS "int dl_matrix3dq_blazeblock_config_t::shortcut"
Shortcut connection flag 
.SS "int dl_matrix3dq_blazeblock_config_t::stride_x"
Strides of width 
.SS "int dl_matrix3dq_blazeblock_config_t::stride_y"
Strides of height 

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
