.TH "face_id_list" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
face_id_list \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBhead\fP"
.br
.ti -1c
.RI "uint8_t \fBtail\fP"
.br
.ti -1c
.RI "uint8_t \fBcount\fP"
.br
.ti -1c
.RI "uint8_t \fBsize\fP"
.br
.ti -1c
.RI "uint8_t \fBconfirm_times\fP"
.br
.ti -1c
.RI "\fBdl_matrix3d_t\fP ** \fBid_list\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint8_t face_id_list::confirm_times"
images needed for one enrolling 
.SS "uint8_t face_id_list::count"
number of enrolled ids 
.SS "uint8_t face_id_list::head"
head index of the id list 
.SS "\fBdl_matrix3d_t\fP** face_id_list::id_list"
stores face id vectors 
.SS "uint8_t face_id_list::size"
max len of id list 
.SS "uint8_t face_id_list::tail"
tail index of the id list 

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
