.TH "landmark_t" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
landmark_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fptp_t \fBlandmark_p\fP [LANDMARKS_NUM]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "fptp_t landmark_t::landmark_p[LANDMARKS_NUM]"
landmark struct 

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
