.TH "lssh_config_t" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lssh_config_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBresized_height\fP"
.br
.ti -1c
.RI "int \fBresized_width\fP"
.br
.ti -1c
.RI "fptp_t \fBy_resize_scale\fP"
.br
.ti -1c
.RI "fptp_t \fBx_resize_scale\fP"
.br
.ti -1c
.RI "int \fBenabled_top_k\fP"
.br
.ti -1c
.RI "fptp_t \fBscore_threshold\fP"
.br
.ti -1c
.RI "fptp_t \fBnms_threshold\fP"
.br
.ti -1c
.RI "dl_conv_mode \fBmode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
