.TH "net_config_t" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
net_config_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "\fBthreshold_config_t\fP \fBthreshold\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int net_config_t::h"
net height 
.SS "\fBthreshold_config_t\fP net_config_t::threshold"
threshold of net 
.SS "int net_config_t::w"
net width 

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
