.TH "tag_face_id_node" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tag_face_id_node \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBtag_face_id_node\fP * \fBnext\fP"
.br
.ti -1c
.RI "char \fBid_name\fP [ENROLL_NAME_LEN]"
.br
.ti -1c
.RI "\fBdl_matrix3d_t\fP * \fBid_vec\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char tag_face_id_node::id_name[ENROLL_NAME_LEN]"
name corresponding to the face id 
.SS "\fBdl_matrix3d_t\fP* tag_face_id_node::id_vec"
face id 
.SS "struct \fBtag_face_id_node\fP* tag_face_id_node::next"
next face id node 

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
