.TH "tag_od_box_list" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tag_od_box_list \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fptp_t * \fBscore\fP"
.br
.ti -1c
.RI "qtp_t * \fBcls\fP"
.br
.ti -1c
.RI "\fBbox_t\fP * \fBbox\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBbox_t\fP* tag_od_box_list::box"
(x1, y1, x2, y2) of the boxes 
.SS "qtp_t* tag_od_box_list::cls"
The class corresponding to the box 
.SS "int tag_od_box_list::len"
The number of the boxes 
.SS "fptp_t* tag_od_box_list::score"
The confidence score of the class corresponding to the box 

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
