.TH "tag_image_list" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tag_image_list \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBimage_box_t\fP * \fBhead\fP"
.br
.ti -1c
.RI "\fBimage_box_t\fP * \fBorigin_head\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBimage_box_t\fP* tag_image_list::head"
The current head of the image_list 
.SS "int tag_image_list::len"
Length of the image_list 
.SS "\fBimage_box_t\fP* tag_image_list::origin_head"
The original head of the image_list 

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
