.TH "threshold_config_t" 3 "Mon Aug 3 2020" "Espressif Audio Development Framework (ESP-ADF)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
threshold_config_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBscore\fP"
.br
.ti -1c
.RI "float \fBnms\fP"
.br
.ti -1c
.RI "int \fBcandidate_number\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int threshold_config_t::candidate_number"
candidate number limitation for each net 
.SS "float threshold_config_t::nms"
nms threshold for nms process 
.SS "float threshold_config_t::score"
score threshold for filter candidates by score 

.SH "Author"
.PP 
Generated automatically by Doxygen for Espressif Audio Development Framework (ESP-ADF) from the source code\&.
