# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/cat_face_detection/lcd:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      temporary: false

examples/cat_face_detection/terminal:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      temporary: false

examples/cat_face_detection/web:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      temporary: false

examples/code_recognition:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      temporary: false

examples/color_detection/lcd:
  enable:
    - if: IDF_TARGET == ["esp32", "esp32s3"]
      temporary: false

examples/esp32-s3-eye:
  enable:
    - if: IDF_TARGET == ["esp32", "esp32s3"]
      temporary: false

examples/human_face_detection/lcd:
  enable:
    - if: IDF_TARGET == ["esp32", "esp32s3"]
      temporary: false

examples/human_face_detection/web:
  enable:
    - if: IDF_TARGET == ["esp32", "esp32s3"]
      temporary: false

examples/human_face_detection/terminal:
  enable:
    - if: IDF_TARGET == ["esp32", "esp32s3"]
      temporary: false

examples/human_face_recognition/lcd:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      temporary: false

examples/human_face_recognition/terminal:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      temporary: false 

examples/motion_detection/lcd:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      temporary: false

examples/motion_detection/web:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      temporary: false

examples/motion_detection/terminal:
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s3"]
      temporary: false